services:
 api:
  build: ./server
  ports:
    - "8000:8000"
  volumes:
    - ./server:/server
  command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
 web:
   build: ./client
   ports:
      - "3000:3000"
   volumes:
      - ./client:/client