import "tw-elements/dist/css/tw-elements.min.css";

export const metadata = {
  title: 'QuickPlot',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
